services:
  web:
    image: flask_open
    build:
      context: .
      network: host
    env_file:
      - .env # This file is optional; defaults will be used if it does not exist
    environment:
      - ORS_URL=http://ors-app:8082
    ports:
      - "8422:8422"
    volumes:
      - ./instance:/app/instance
      - ./san-diego.osm.pbf:/app/san-diego.osm.pbf:ro
    command: >
      sh -c "python scripts/extract_cameras.py /app/san-diego.osm.pbf &&
      gunicorn 'flaskr:create_app()'"
    restart: unless-stopped
    depends_on:
      - ors-app

  ors-app:
    container_name: ors-app
    image: openrouteservice/openrouteservice:v9.8.0
    volumes:
      - ./ors/ors-docker:/home/ors
      - ./ors-config.yml:/home/ors/config/ors-config.yml
      - ./san-diego.osm.pbf:/home/ors/files/socal.osm.pbf
    environment:
      ORS_CONFIG_LOCATION: /home/ors/config/ors-config.yml
      REBUILD_GRAPHS: "True"
      CONTAINER_LOG_LEVEL: INFO
      XMS: 1g
      XMX: 2g
      ADDITIONAL_JAVA_OPTS: ""
